controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

articles_index :
    path: /articles
    controller : App\Controller\ArticlesController::index


articles_show :
    path: /articles/{id}
    controller : App\Controller\ArticlesController::show
    requirements:
        id: \d+
